<?php

namespace App\Exports;

use App\Models\StocksCount;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithEvents;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use Maatwebsite\Excel\Events\AfterSheet;
use Illuminate\Support\Facades\Auth;

class StocksCountExport implements FromArray, WithHeadings, WithTitle, WithStyles, WithEvents
{
    /**
     * Prepare and sort data before exporting.
     */
    public function array(): array
    {
        $stocks = StocksCount::all();
        $exportData = [];

        foreach ($stocks as $stock) {
            $exportData[] = [
                $stock->item_name,
                $stock->quantity . ' pcs',
                $stock->remarks ?? '',
            ];
        }

        return $exportData;
    }

    /**
     * Define table headers.
     */
    public function headings(): array
    {
        return [
            ['OREMPCO EMPLOYEES MULTI-PURPOSE COOPERATIVE (OREMPCO)'],
            ['Calapan City, Oriental Mindoro'],
            ['Registration No.: 9520-04002679'],
            ['NVAT-Exempt TIN: 004-175-226-000'],
            [''],
            ['PHYSICAL INVENTORY COUNT FORM'],
            ['PRODUCT: WATER', 'DATE OF INVENTORY: ' . now()->format('m/d/Y')],
            [''],
            ['ITEM', 'QUANTITY', 'REMARKS'],
        ];
    }

    /**
     * Set the worksheet title.
     */
    public function title(): string
    {
        return 'Stocks Count';
    }

    /**
     * Apply base styles to the sheet.
     */
    public function styles(Worksheet $sheet)
    {
        return [
            1 => ['font' => ['bold' => true, 'size' => 14, 'name' => 'Arial'], 'alignment' => ['horizontal' => 'center']],
            2 => ['font' => ['italic' => true, 'size' => 12, 'name' => 'Arial'], 'alignment' => ['horizontal' => 'center']],
            3 => ['font' => ['size' => 12, 'name' => 'Arial'], 'alignment' => ['horizontal' => 'center']],
            4 => ['font' => ['size' => 12, 'name' => 'Arial'], 'alignment' => ['horizontal' => 'center']],
            6 => ['font' => ['bold' => true, 'size' => 16, 'name' => 'Arial'], 'alignment' => ['horizontal' => 'center']],
            9 => [
                'font' => ['bold' => true, 'name' => 'Arial'],
                'alignment' => ['horizontal' => 'center'],
                'borders' => ['bottom' => ['borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK]],
                'fill' => ['fillType' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID, 'startColor' => ['rgb' => 'FFFF00']],
            ],
        ];
    }

    /**
     * Apply borders, images, footer, and more.
     */
    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {
                $sheet = $event->sheet->getDelegate();

                // Merge header cells
                foreach (range(1, 6) as $row) {
                    $sheet->mergeCells("A{$row}:C{$row}");
                }

                // Merge cells for PRODUCT and DATE
                $sheet->mergeCells("A7:C7");

                // Freeze header
                $sheet->freezePane('A10');

                // Adjust column widths to match title
                $sheet->getColumnDimension('A')->setWidth(40);
                $sheet->getColumnDimension('B')->setWidth(25);
                $sheet->getColumnDimension('C')->setWidth(35);

                // Apply borders and styles
                $lastRow = $sheet->getHighestRow();
                $cellRange = 'A9:C' . $lastRow;

                $sheet->getStyle($cellRange)->applyFromArray([
                    'font' => ['name' => 'Arial', 'size' => 11],
                    'borders' => ['allBorders' => ['borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN]],
                    'alignment' => [
                        'horizontal' => \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_LEFT,
                        'vertical' => \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER,
                        'indent' => 2,
                        'wrapText' => true,
                    ],
                ]);

                // Footer
                $generatedOn = now()->format('F d, Y h:i A');
                $generatedBy = Auth::guard('sales')->user()->full_name ?? 'System';
                $footerRow = $lastRow + 3;

                $sheet->setCellValue("B{$footerRow}", "Generation Date:");
                $sheet->setCellValue("C{$footerRow}", $generatedOn);
                $sheet->setCellValue("B" . ($footerRow + 1), "Generated by:");
                $sheet->setCellValue("C" . ($footerRow + 1), $generatedBy);

                $sheet->getStyle("B{$footerRow}:C" . ($footerRow + 1))->applyFromArray([
                    'font' => ['italic' => true, 'name' => 'Arial', 'size' => 11],
                    'alignment' => ['horizontal' => \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_LEFT],
                ]);

                // Logo
                $drawing = new Drawing();
                $drawing->setName('OREMPCO Logo');
                $drawing->setDescription('Company Logo');
                $drawing->setPath(public_path('images/orempcologo.png'));
                $drawing->setHeight(80);
                $drawing->setCoordinates('A1');
                $drawing->setOffsetX(10);
                $drawing->setWorksheet($sheet);
            },
        ];
    }
}
