<!DOCTYPE html>
<html>
<head>
    <title>OREMPCO Water Station - Physical Inventory Count</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            position: relative;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h2, .header h4 {
            margin: 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        table, th, td {
            border: 1px solid #000;
        }
        th, td {
            padding: 8px 12px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        thead {
            display: table-header-group;
        }
        .footer {
            position: fixed;
            bottom: 20px;
            right: 30px;
            font-size: 10px;
            text-align: right;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header" style="display: flex; align-items: center; justify-content: center; gap: 20px;">
        <!-- Logo -->
        <div>
            <img src="{{ public_path('images/orempcologo.png') }}" alt="OREMPCO Logo" style="width: 80px; height: auto;">
        </div>

        <!-- Title and Details -->
        <div style="text-align: center;">
            <h2>ORMECO EMPLOYEES MULTI-PURPOSE COOPERATIVE (OREMPCO)</h2>
            <h4>Sta. Isabel, Calapan City, Oriental Mindoro</h4>
            <h4>CDA Registration No.: 9520-04002679</h4>
            <h4>NVAT-Exempt TIN: 004-175-226-000</h4>
            <h3 style="margin-top: 20px;">PHYSICAL INVENTORY COUNT FORM</h3>
        </div>
    </div>

    <!-- Inventory Details -->
    <p><strong>Product:</strong> WATER | <strong>Date of Inventory:</strong> {{ \Carbon\Carbon::now()->format('m/d/Y') }}</p>

    <!-- Stocks Table -->
    <table>
        <thead>
            <tr>
                <th>ITEM</th>
                <th>QUANTITY</th>
                <th>REMARKS</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stocks as $stock)
                <tr>
                    <td>{{ $stock['item_name'] }}</td>
                    <td style="text-align: right;">{{ $stock['quantity'] }}</td>
                    <td>{{ $stock['remarks'] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        <p>Generation Date: {{ \Carbon\Carbon::now()->format('F d, Y h:i A') }}</p>
        <p>Generated by: {{ Auth::guard('sales')->user()->full_name }}</p>
    </div>
</body>
</html>
