<!DOCTYPE html>
<html>
<head>
    <title>OREMPCO - Physical Inventory Count</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            position: relative;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h2, .header h4 {
            margin: 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            table-layout: fixed;
        }
        th, td {
            border: 1px solid #000;
            padding: 8px 12px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .footer {
            position: fixed;
            bottom: 20px;
            right: 30px;
            font-size: 10px;
            text-align: right;
        }
        .inventory-details {
            display: flex;
            justify-content: space-between;
            margin-bottom: 10px;
            font-weight: bold;
        }
        .total-expense {
            font-weight: bold;
            text-align: right;
            padding: 10px;
            margin-top: 5px;
            border-top: 2px solid #000;
        }
        .column-item { width: 40%; }
        .column-quantity { width: 20%; }
        .column-price { width: 20%; }
        .column-remarks { width: 20%; }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header" style="display: flex; align-items: center; justify-content: center; gap: 20px;">
        <!-- Logo -->
        <div>
            <img src="{{ public_path('images/orempcologo.png') }}" alt="OREMPCO Logo" style="width: 80px; height: auto;">
        </div>

        <!-- Title and Details -->
        <div style="text-align: center;">
            <h2>ORMECO EMPLOYEES MULTI-PURPOSE COOPERATIVE (OREMPCO)</h2>
            <h4>Sta. Isabel, Calapan City, Oriental Mindoro</h4>
            <h4>CDA Registration No.: 9520-04002679</h4>
            <h4>NVAT-Exempt TIN: 004-175-226-000</h4>
            <h3 style="margin-top: 20px;">PHYSICAL INVENTORY COUNT FORM</h3>
        </div>
    </div>

    <!-- Inventory Details -->
    <p><strong>Date of Inventory:</strong> {{ \Carbon\Carbon::now()->format('m/d/Y') }}</p>

    @foreach($categories as $category)
        <div class="inventory-details">
            <p><strong>Category:</strong> {{ $category->name }}</p>
        </div>

        <!-- Stocks Table -->
        <table>
            <thead>
                <tr>
                    <th class="column-item">ITEM</th>
                    <th class="column-quantity">QUANTITY</th>
                    <th class="column-price">PRICE</th>
                    <th class="column-remarks">REMARKS</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $totalExpense = 0;
                @endphp
                @foreach($category->stockCounts as $stock)
                    @php
                        $totalExpense += $stock->price; // Sum of all item prices
                    @endphp
                    <tr>
                        <td class="column-item">{{ $stock->item_name }}</td>
                        <td class="column-quantity">
                            {{ $stock->quantity }} {{ $stock->unit_of_measurement ?? '' }}
                        </td>
                        <td class="column-price">{{ number_format($stock->price, 2) }}</td>
                        <td class="column-remarks">{{ $stock->remarks }}</td>
                    </tr>
                @endforeach
                <tr>
                    <td colspan="3" class="total-expense">Total Expense for {{ $category->name }}:</td>
                    <td class="total-expense">{{ number_format($totalExpense, 2) }}</td>
                </tr>
            </tbody>
        </table>
    @endforeach

    <!-- Footer -->
    <div class="footer">
        <p>Generation Date: {{ \Carbon\Carbon::now()->format('F d, Y h:i A') }}</p>
        <p>Generated by: {{ Auth::guard('sales')->user()->full_name }}</p>
    </div>
</body>
</html>
